[package]
name = "hroverlay"
version = "0.1.0"
authors = ["jackson"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
btleplug = "0.5.4"
